CREATE DATABASE test_database;
CREATE USER qweuser WITH PASSWORD 'qwe';
GRANT CONNECT,TEMPORARY ON DATABASE seo TO qweuser;
GRANT SELECT, UPDATE, INSERT,DELETE, TRUNCATE ON ALL TABLES in schema public TO qweuser;
GRANT SELECT, USAGE  ON ALL SEQUENCES in schema public TO qweuser;
