SELECT 
U.URL, 
P.PARAM, 
P.DATE_CREATE
FROM 
htmls H 
JOIN urls U 
ON U.URL_ID = H.URL_ID 
JOIN params P 
ON P.HTML_ID = H.HTML_ID 
WHERE 
P.CONDITION_ID = $1 
AND U.URL_ID = $2 
ORDER BY H.DATE_CREATE DESC LIMIT 1;
